"""
Data Dictionary Generator

Reads profiling reports and generates a Markdown
data dictionary for all datasets.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.core.config import (
    PROFILING_REPORTS_DIR,
    DOCS_DIR,
)
from app.core.logger import get_logger

logger = get_logger(__name__)


class DataDictionaryGenerator:
    """
    Generates a Markdown data dictionary from
    dataset profiling reports.
    """

    def __init__(self) -> None:
        self.profile_dir: Path = PROFILING_REPORTS_DIR
        self.output_file: Path = DOCS_DIR / "DATA_DICTIONARY.md"

    def discover_reports(self) -> list[Path]:
        """
        Discover all profiling reports.
        """

        reports = list(self.profile_dir.glob("*_profile.json"))

        logger.info(
            "Discovered %d profiling reports.",
            len(reports),
        )

        return reports
    
    def load_report(self, report_path: Path) -> dict:
        """
        Load a profiling report from disk.

        Parameters
        ----------
        report_path : Path
            Path to the profiling report.

        Returns
        -------
        dict
            Loaded profiling report.
        """

        try:
            logger.info("Loading report: %s", report_path.name)

            with open(report_path, "r", encoding="utf-8") as file:
                report = json.load(file)

            logger.info("Successfully loaded: %s", report_path.name)

            return report

        except Exception:
            logger.exception(
                "Failed to load report: %s",
                report_path.name,
            )
            raise

    def generate_markdown(
        self,
        reports: list[dict],
    ) -> str:
        """
        Generate Markdown documentation from profiling reports.

        Parameters
        ----------
        reports : list[dict]
            List of profiling reports.

        Returns
        -------
        str
            Markdown content.
        """

        markdown = "# Data Dictionary\n\n"
        markdown += (
            "This document is automatically generated by the "
            "CommerceFlow Data Dictionary Generator.\n\n"
        )

        for report in reports:

            markdown += f"## {report['dataset_name']}\n\n"

            markdown += f"- **Rows:** {report['rows']}\n"
            markdown += f"- **Columns:** {report['columns']}\n"
            markdown += (
                f"- **Memory Usage:** "
                f"{report['memory_usage_mb']} MB\n"
            )
            markdown += (
                f"- **Duplicate Rows:** "
                f"{report['duplicate_rows']}\n\n"
            )

            markdown += (
                "| Column | Data Type | Missing | "
                "Missing % | Unique Values |\n"
            )

            markdown += (
                "|--------|-----------|---------|"
                "-----------|---------------|\n"
            )

            for column, details in report["column_profiles"].items():

                markdown += (
                    f"| {column} "
                    f"| {details['data_type']} "
                    f"| {details['missing_values']} "
                    f"| {details['missing_percentage']}% "
                    f"| {details['unique_values']} |\n"
                )

            markdown += "\n---\n\n"

        return markdown 

    def save_dictionary(
        self,
        markdown: str,
    ) -> None:
        """
        Save the generated Markdown data dictionary.
        """

        with open(
            self.output_file,
            "w",
            encoding="utf-8",
        ) as file:
            file.write(markdown)

        logger.info(
            "Data dictionary saved: %s",
            self.output_file.name,
        )   

    def run(self) -> None:

        logger.info("=" * 60)
        logger.info("Starting Data Dictionary Generator")
        logger.info("=" * 60)

        report_files = self.discover_reports()

        reports = []

        for report_path in report_files:
            report = self.load_report(report_path)
            reports.append(report)

        markdown = self.generate_markdown(reports)

        self.save_dictionary(markdown)

        logger.info("=" * 60)
        logger.info("Data Dictionary Generated Successfully")
        logger.info("=" * 60)


def main() -> None:
    generator = DataDictionaryGenerator()
    generator.run()


if __name__ == "__main__":
    main()