/*
===============================================================================
File Name   : 03_top_products.sql
Project     : CommerceFlow
Module      : Analytics Layer
Author      : Dhruv Kajla

===============================================================================
BUSINESS QUESTION
===============================================================================

Q. Which product categories generate the highest revenue?

Additionally,

• How many order items were sold?
• What is the total revenue generated by each category?
• What is the average customer payment for each category?

This report helps identify the most profitable product categories.

Examples

• Amazon identifies high-performing categories.
• Flipkart analyzes seasonal demand.
• Marketing teams decide where to invest advertising.
• Inventory teams prioritize stock replenishment.

===============================================================================
WHY THIS QUERY EXISTS
===============================================================================

Not every product category contributes equally to revenue.

Some categories:

• Sell frequently
• Generate higher revenue
• Have higher average selling prices

Understanding these differences helps businesses:

✓ Optimize inventory
✓ Improve marketing campaigns
✓ Increase profitability
✓ Forecast demand

===============================================================================
TABLES USED
===============================================================================

1. public.fact_orders

Purpose
-------
Stores transactional sales data.

Important Columns

product_key
payment_value

------------------------------------------------------------

2. public.dim_products

Purpose
-------
Stores product-related descriptive information.

Important Columns

product_key
product_category_name

Why?

Instead of showing meaningless Product IDs, we display
human-readable product categories.

===============================================================================
WHY DO WE JOIN THESE TABLES?
===============================================================================

fact_orders contains

product_key

↓

Only an integer surrogate key

Example

15

This number has no business meaning.

------------------------------------------------------------

dim_products contains

15

↓

"esporte_lazer"

Now the report becomes understandable.

This is exactly why Data Warehouses use Dimension Tables.

===============================================================================
SQL CONCEPTS USED
===============================================================================

1. INNER JOIN

Purpose
-------
Combines sales transactions with product information.

Why?

Revenue exists inside fact_orders.

Category name exists inside dim_products.

Joining both tables creates a complete business report.

------------------------------------------------------------

2. COUNT(*)

Purpose
-------
Counts order-item records.

Why?

Shows how many products from each category were sold.

Higher count

↓

Higher sales volume.

------------------------------------------------------------

3. SUM(payment_value)

Purpose
-------
Calculates total revenue.

Why?

Revenue equals the total amount customers paid.

------------------------------------------------------------

4. AVG(payment_value)

Purpose
-------
Calculates average payment.

Why?

Shows the average amount customers spend in each category.

Higher average

↓

Premium category.

------------------------------------------------------------

5. GROUP BY

Purpose
-------
Creates one summary row for each product category.

Without GROUP BY

↓

Only one total revenue value.

With GROUP BY

↓

One revenue value for every category.

------------------------------------------------------------

6. ORDER BY

Purpose
-------
Sorts categories.

Why?

Business users usually want to see

Highest Revenue

↓

Lowest Revenue

------------------------------------------------------------

7. LIMIT

Purpose
-------
Returns only the Top 10 categories.

Why?

Dashboards rarely display hundreds of rows.

Top performers are the most important.

===============================================================================
QUERY EXECUTION ORDER
===============================================================================

Step 1

FROM fact_orders

↓

Read transaction records.

------------------------------------------------------------

Step 2

INNER JOIN dim_products

↓

Attach product category information.

------------------------------------------------------------

Step 3

GROUP BY product_category_name

↓

Create one group per category.

------------------------------------------------------------

Step 4

COUNT()
SUM()
AVG()

↓

Calculate business KPIs.

------------------------------------------------------------

Step 5

ORDER BY revenue DESC

↓

Sort highest revenue first.

------------------------------------------------------------

Step 6

LIMIT 10

↓

Return only the Top 10 categories.

===============================================================================
BUSINESS INSIGHTS
===============================================================================

This report helps answer:

✓ Which categories make the most money?

✓ Which categories sell the most?

✓ Which categories have premium-priced products?

A category with

High Revenue
Low Order Count

usually indicates

↓

High-value products.

A category with

High Order Count
Low Revenue

usually indicates

↓

Low-cost products sold in large quantities.

===============================================================================
PERFORMANCE CONSIDERATIONS
===============================================================================

Indexes Used

✓ fact_orders.product_key

Primary Key

✓ dim_products.product_key

Join Performance

The join occurs on indexed surrogate keys,
which is much faster than joining text columns.

Complexity

Approximately

O(n)

where n is the number of rows in fact_orders.

===============================================================================
INTERVIEW EXPLANATION
===============================================================================

If asked:

"Explain this query."

You can answer:

"This query joins the fact_orders table with the
dim_products dimension using the surrogate product_key.
After enriching each transaction with its product category,
the data is grouped by category to calculate total sales,
revenue, and average payment. Finally, the results are
sorted by revenue and the Top 10 categories are returned.
This is a common analytical pattern in star-schema data
warehouses."

===============================================================================
FUTURE IMPROVEMENTS
===============================================================================

• Revenue by Product
• Revenue by Category & Month
• Category Growth Rate
• Category Ranking using RANK()
• Running Revenue using Window Functions
• Top Categories by Profit (when cost data becomes available)
it also give rank to each category based on revenue.

===============================================================================
*/

SELECT
    ROW_NUMBER() OVER (
        ORDER BY SUM(f.payment_value) DESC
    ) AS revenue_rank,

    p.product_category_name,

    COUNT(*) AS total_order_items,

    ROUND(SUM(f.payment_value), 2) AS total_revenue,

    ROUND(AVG(f.payment_value), 2) AS average_payment

FROM public.fact_orders AS f

INNER JOIN public.dim_products AS p
    ON f.product_key = p.product_key

GROUP BY
    p.product_category_name

ORDER BY
    total_revenue DESC

LIMIT 10;