/*
===============================================================================
File Name   : 05_top_sellers.sql
Project     : CommerceFlow
Module      : Analytics Layer
Author      : Dhruv Kajla

===============================================================================
BUSINESS QUESTION
===============================================================================

Q. Which sellers generate the highest revenue on the platform?

Additionally,

• How many order items has each seller sold?
• What is the total revenue generated by each seller?
• What is the average payment received per order item?
• Which city and state do the top-performing sellers belong to?

Marketplace businesses use this report to identify their most valuable
selling partners.

Examples

• Amazon identifies top merchants.
• Flipkart rewards high-performing sellers.
• Mercado Livre monitors seller performance.
• Operations teams identify strategic business partners.

===============================================================================
WHY THIS QUERY EXISTS
===============================================================================

In a marketplace, thousands of sellers contribute to overall revenue.

However,

• Some sellers generate significantly higher revenue.
• Some sell many low-cost products.
• Others sell fewer but premium-priced products.

Understanding seller performance helps businesses:

✓ Reward top-performing sellers
✓ Improve seller retention
✓ Identify strategic partners
✓ Optimize marketplace growth
✓ Build seller incentive programs

===============================================================================
TABLES USED
===============================================================================

1. public.fact_orders

Purpose
-------
Stores transactional sales information.

Important Columns

seller_key
payment_value

------------------------------------------------------------

2. public.dim_sellers

Purpose
-------
Stores seller-related descriptive information.

Important Columns

seller_id
seller_city
seller_state

===============================================================================
WHY DO WE JOIN THESE TABLES?
===============================================================================

fact_orders stores

seller_key

↓

Surrogate Key

Example

125

This number has no business meaning.

Joining dim_sellers provides

• Seller ID
• Seller City
• Seller State

making the report meaningful for business users.

===============================================================================
SQL CONCEPTS USED
===============================================================================

1. INNER JOIN

Purpose
-------
Combines sales data with seller information.

------------------------------------------------------------

2. GROUP BY

Creates one summary row for each seller.

------------------------------------------------------------

3. COUNT(*)

Counts total order items sold.

------------------------------------------------------------

4. SUM(payment_value)

Calculates total revenue generated by each seller.

------------------------------------------------------------

5. AVG(payment_value)

Calculates average payment received per order item.

------------------------------------------------------------

6. COALESCE()

Purpose
-------
Replaces NULL values with 0.

Why?

If a seller has missing payment records,
business reports should display 0 instead of NULL.

------------------------------------------------------------

7. ORDER BY DESC

Sorts sellers from highest revenue to lowest.

------------------------------------------------------------

8. LIMIT

Returns only the Top 10 sellers.

===============================================================================
QUERY EXECUTION ORDER
===============================================================================

Step 1

FROM fact_orders

↓

Read transactional records.

------------------------------------------------------------

Step 2

INNER JOIN dim_sellers

↓

Attach seller information.

------------------------------------------------------------

Step 3

GROUP BY seller_id

↓

Create one group per seller.

------------------------------------------------------------

Step 4

COUNT()
SUM()
AVG()

↓

Calculate seller KPIs.

------------------------------------------------------------

Step 5

ORDER BY revenue DESC

↓

Sort highest-performing sellers first.

------------------------------------------------------------

Step 6

LIMIT 10

↓

Return Top 10 sellers.

===============================================================================
BUSINESS INSIGHTS
===============================================================================

This report answers:

✓ Who are the highest-revenue sellers?

✓ Which sellers have the largest sales volume?

✓ Which sellers operate from which cities?

✓ Which sellers contribute most to marketplace revenue?

A seller with

High Revenue
Low Order Count

usually sells premium products.

A seller with

High Order Count
Moderate Revenue

usually focuses on high-volume sales.

===============================================================================
PERFORMANCE CONSIDERATIONS
===============================================================================

Join Key

fact_orders.seller_key

↓

dim_sellers.seller_key

The join uses integer surrogate keys,
making it efficient for large datasets.

Approximate Complexity

O(n)

===============================================================================
INTERVIEW EXPLANATION
===============================================================================

If asked:

"Explain this query."

You can answer:

"This query joins the fact_orders table with the
dim_sellers dimension using the surrogate seller_key.
The data is grouped by seller_id to calculate order-item
count, total revenue, and average payment. The results
are sorted in descending order of revenue to identify the
Top 10 sellers. This type of report is commonly used in
marketplace businesses to evaluate seller performance."

===============================================================================
FUTURE IMPROVEMENTS
===============================================================================

• Seller Revenue by Month

• Seller Growth Rate

• Top Sellers by State

• Average Order Value per Seller

• Seller Performance Ranking using RANK()

• Seller Contribution Percentage

===============================================================================
*/

SELECT
    s.seller_id,
    s.seller_city,
    s.seller_state,

    COUNT(*) AS total_order_items,

    ROUND(COALESCE(SUM(f.payment_value), 0), 2) AS total_revenue,

    ROUND(COALESCE(AVG(f.payment_value), 0), 2) AS average_payment

FROM public.fact_orders AS f

INNER JOIN public.dim_sellers AS s
    ON f.seller_key = s.seller_key

GROUP BY
    s.seller_id,
    s.seller_city,
    s.seller_state

ORDER BY
    total_revenue DESC

LIMIT 10;