/*
===============================================================================
File Name   : 06_revenue_by_state.sql
Project     : CommerceFlow
Module      : Analytics Layer
Author      : Dhruv Kajla

===============================================================================
BUSINESS QUESTION
===============================================================================

Q. Which customer states generate the highest revenue?

Additionally,

• How many order items were purchased from each state?
• What is the total revenue generated by each state?
• What is the average customer payment in each state?

Businesses use this report to understand their strongest regional markets.

Examples

• Amazon identifies high-performing states.
• Marketing teams allocate advertising budgets by region.
• Logistics teams optimize warehouse placement.
• Sales teams identify growth opportunities.

===============================================================================
WHY THIS QUERY EXISTS
===============================================================================

Customer purchasing behavior differs across regions.

Some states:

• Generate high revenue
• Place more orders
• Have higher average order values

Understanding regional performance helps businesses:

✓ Identify top-performing markets
✓ Optimize logistics
✓ Allocate marketing budgets
✓ Forecast regional demand
✓ Expand into high-potential areas

===============================================================================
TABLES USED
===============================================================================

1. public.fact_orders

Purpose
-------
Stores transactional sales data.

Important Columns

customer_key
payment_value

------------------------------------------------------------

2. public.dim_customers

Purpose
-------
Stores customer information.

Important Columns

customer_state
customer_city

===============================================================================
WHY DO WE JOIN THESE TABLES?
===============================================================================

fact_orders contains

customer_key

↓

Surrogate Key

Joining dim_customers allows us to analyze sales geographically.

===============================================================================
SQL CONCEPTS USED
===============================================================================

1. INNER JOIN

Purpose
-------
Combines transactional data with customer information.

------------------------------------------------------------

2. GROUP BY

Creates one summary row for each state.

------------------------------------------------------------

3. COUNT(*)

Counts total order items.

------------------------------------------------------------

4. SUM(payment_value)

Calculates total revenue generated by each state.

------------------------------------------------------------

5. AVG(payment_value)

Calculates average payment.

------------------------------------------------------------

6. COALESCE()

Replaces NULL values with 0.

------------------------------------------------------------

7. ORDER BY DESC

Sorts states from highest revenue to lowest.

===============================================================================
QUERY EXECUTION ORDER
===============================================================================

1. Read fact_orders

↓

2. Join dim_customers

↓

3. Group by customer_state

↓

4. Calculate KPIs

↓

5. Sort by revenue

===============================================================================
BUSINESS INSIGHTS
===============================================================================

This report answers:

✓ Which states contribute the most revenue?

✓ Which regions have the largest customer base?

✓ Which states should receive more marketing investment?

✓ Which regions have the highest average order value?

===============================================================================
PERFORMANCE CONSIDERATIONS
===============================================================================

Join Key

fact_orders.customer_key

↓

dim_customers.customer_key

Uses indexed surrogate keys for efficient joins.

Approximate Complexity

O(n)

===============================================================================
INTERVIEW EXPLANATION
===============================================================================

If asked:

"Explain this query."

You can answer:

"This query joins the fact_orders table with the
dim_customers dimension using the surrogate customer_key.
The data is grouped by customer_state to calculate total
orders, revenue, and average payment for each state.
The results are sorted by revenue to identify the highest-
performing regions."

===============================================================================
FUTURE IMPROVEMENTS
===============================================================================

• Revenue by City

• Revenue by Region

• Monthly Revenue by State

• Top Customers within each State

• State Contribution Percentage

===============================================================================
*/

SELECT
    c.customer_state,

    COUNT(*) AS total_order_items,

    ROUND(COALESCE(SUM(f.payment_value), 0), 2) AS total_revenue,

    ROUND(COALESCE(AVG(f.payment_value), 0), 2) AS average_payment

FROM public.fact_orders AS f

INNER JOIN public.dim_customers AS c
    ON f.customer_key = c.customer_key

GROUP BY
    c.customer_state

ORDER BY
    total_revenue DESC;