/*
===============================================================================
File Name   : 10_top_product_category_per_state.sql
Project     : CommerceFlow
Module      : Analytics Layer
Author      : Dhruv Kajla

===============================================================================
BUSINESS QUESTION
===============================================================================

Q. Which product category generates the highest revenue in each state?

Additionally,

• What is the revenue generated by the top product category?
• Which product category dominates each state's market?
• How can businesses optimize inventory based on regional demand?

This report helps businesses understand regional purchasing behavior
and optimize inventory, marketing campaigns, and warehouse stocking.

===============================================================================
WHY THIS QUERY EXISTS
===============================================================================

Knowing the overall best-selling category is useful, but businesses often
need to understand local preferences.

For example:

• Electronics may dominate one state.
• Furniture may dominate another.
• Beauty products may perform best elsewhere.

This report identifies the highest revenue-generating category in every
state.

===============================================================================
TABLES USED
===============================================================================

1. public.fact_orders

Purpose
-------
Stores transaction-level revenue.

Important Columns

product_key
customer_key
payment_value

------------------------------------------------------------

2. public.dim_products

Purpose
-------
Stores product information.

Important Columns

product_category_name

------------------------------------------------------------

3. public.dim_customers

Purpose
-------
Stores customer location.

Important Columns

customer_state

===============================================================================
WHY THESE TABLES?
===============================================================================

fact_orders contains revenue.

dim_products provides product category.

dim_customers provides state information.

Combining these tables allows regional product performance analysis.

===============================================================================
SQL CONCEPTS USED
===============================================================================

1. INNER JOIN

Joins fact table with dimensions.

------------------------------------------------------------

2. GROUP BY

Calculates revenue for every

State + Product Category

------------------------------------------------------------

3. SUM()

Calculates revenue.

------------------------------------------------------------

4. ROW_NUMBER()

Ranks product categories.

------------------------------------------------------------

5. PARTITION BY

Creates separate rankings for every state.

------------------------------------------------------------

6. CTE

Improves readability.

===============================================================================
NEW SQL CONCEPT
===============================================================================

ROW_NUMBER()

Assigns sequential ranking.

Example

State      Category      Revenue     Rank

SP         Furniture      500K        1

SP         Electronics    450K        2

SP         Sports         300K        3

RJ         Beauty         200K        1

RJ         Toys           180K        2

Notice that ranking restarts for every state.

This happens because of

PARTITION BY customer_state

===============================================================================
WINDOW FUNCTION EXPLANATION
===============================================================================

ROW_NUMBER()

OVER(

PARTITION BY customer_state

ORDER BY total_revenue DESC

)

Meaning

For every state

↓

Sort categories by revenue

↓

Assign Rank 1

↓

Rank 2

↓

Rank 3

===============================================================================
QUERY EXECUTION ORDER
===============================================================================

Read fact_orders

↓

Join Customers

↓

Join Products

↓

Group by State + Category

↓

Calculate Revenue

↓

Apply ROW_NUMBER()

↓

Return Rank = 1

===============================================================================
BUSINESS INSIGHTS
===============================================================================

This report identifies:

✓ Best product category in every state

✓ Regional purchasing preferences

✓ Inventory planning opportunities

✓ Marketing optimization

===============================================================================
PERFORMANCE CONSIDERATIONS
===============================================================================

Uses:

GROUP BY

+

ROW_NUMBER()

Efficient for analytical workloads.

===============================================================================
INTERVIEW EXPLANATION
===============================================================================

If asked,

"Why use ROW_NUMBER()?"

Answer:

"ROW_NUMBER() ranks rows within each partition.
Here, PARTITION BY creates independent rankings for every state, allowing
us to identify the highest revenue-generating product category in each
state."

===============================================================================
FUTURE IMPROVEMENTS
===============================================================================

• Top 3 Categories per State

• Category Growth by Month

• Top Category by City

• Category Revenue Share

===============================================================================
*/

WITH state_category_revenue AS (

    SELECT

        c.customer_state,

        p.product_category_name,

        ROUND(SUM(f.payment_value),2) AS total_revenue

    FROM public.fact_orders AS f

    INNER JOIN public.dim_customers AS c
        ON f.customer_key = c.customer_key

    INNER JOIN public.dim_products AS p
        ON f.product_key = p.product_key

    GROUP BY

        c.customer_state,
        p.product_category_name

),

ranked_categories AS (

    SELECT

        customer_state,

        product_category_name,

        total_revenue,

        ROW_NUMBER() OVER(

            PARTITION BY customer_state

            ORDER BY total_revenue DESC

        ) AS rank

    FROM state_category_revenue

)

SELECT

    customer_state,

    product_category_name,

    total_revenue

FROM ranked_categories

WHERE rank = 1

ORDER BY total_revenue DESC;